---
  - name: Install apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: Enable apache2 service
    service:
      name: apache2
      state: started
      enabled: yes
  - name: Generatating index.html
    copy:
      dest: "/var/www/html/index.html"
      content: |
        CPU model: {{ ansible_processor[2] }}
        RAM(total): {{ ansible_memtotal_mb }}Mi
        Disk size(total): {{ ansible_devices.sda.size }}
        IP adress: {{ ansible_enp0s3.ipv4.address }}
    notify:
      - Restart apache2
  - name: Get status
    uri:
      url: http://localhost